#!/usr/bin/env php
<?php
	require __DIR__.'/vendor/autoload.php';
	use Symfony\Component\Console\Application;
	// load all commands here from an external php file
	$commands  = require('app/bin/commands_list.php');
	
	$application = new Application();
	
	foreach ($commands as $class) {
		if (!class_exists($class)) {
			throw new RuntimeException(sprintf('Class %s does not exist', $class));
		}
		$command = new $class();
		$application->add($command);
	}
	
	$application->run();


?>